// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using phucvucongdong.Data;

#nullable disable

namespace phucvucongdong.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250309140205_UpdateHoatdong-diemtieuchi")]
    partial class UpdateHoatdongdiemtieuchi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThamGiaSinhVien", b =>
                {
                    b.Property<int>("sinh_vien_id")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("hoat_dong_id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("minh_chung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sinh_vien_id", "hoat_dong_id");

                    b.HasIndex("hoat_dong_id");

                    b.ToTable("ThamGiaSinhVien", "pvcd", t =>
                        {
                            t.HasCheckConstraint("CK_ThamGiaSinhVien_TrangThai", "[TrangThai] IN ('Hoàn thành','Chưa hoàn thành')");
                        });
                });

            modelBuilder.Entity("phucvucongdong.Entities.DangKyGiaoVien", b =>
                {
                    b.Property<int>("giao_vien_id")
                        .HasColumnType("int");

                    b.Property<int>("hoat_dong_id")
                        .HasColumnType("int");

                    b.Property<int>("nam_hoc")
                        .HasColumnType("int");

                    b.Property<int?>("diem")
                        .HasColumnType("int");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("giao_vien_id", "hoat_dong_id", "nam_hoc");

                    b.HasIndex("hoat_dong_id");

                    b.ToTable("DangKyGiaoVien", "pvcd", t =>
                        {
                            t.HasCheckConstraint("CK_DangKyGiaoVien_TrangThai", "[TrangThai] IN ('0', '1', '2')");
                        });
                });

            modelBuilder.Entity("phucvucongdong.Entities.DanhMucPVCongDong", b =>
                {
                    b.Property<int>("danh_muc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("danh_muc_id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("mo_ta")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ten_danh_muc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("danh_muc_id");

                    b.ToTable("DanhMucPVCongDong", "pvcd");
                });

            modelBuilder.Entity("phucvucongdong.Entities.GiaoVien", b =>
                {
                    b.Property<int>("giao_vien_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("giao_vien_id"));

                    b.Property<string>("chuc_vu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("nguoi_dung_id")
                        .HasColumnType("int");

                    b.HasKey("giao_vien_id");

                    b.HasIndex("nguoi_dung_id");

                    b.ToTable("GiaoVien");
                });

            modelBuilder.Entity("phucvucongdong.Entities.HoatDong", b =>
                {
                    b.Property<int>("hoat_dong_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hoat_dong_id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("mo_ta")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ngay_bat_dau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_ket_thuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_hoat_dong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("tieu_chi_id")
                        .HasColumnType("int");

                    b.HasKey("hoat_dong_id");

                    b.HasIndex("tieu_chi_id");

                    b.ToTable("HoatDong", "pvcd");
                });

            modelBuilder.Entity("phucvucongdong.Entities.HoatDongDotXuat", b =>
                {
                    b.Property<int>("nguoi_dung_id")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("ten_hoat_dong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.Property<int>("nam_hoc")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("hoc_ky")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<string>("minh_chung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("mo_ta")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("nguoi_dung_id", "ten_hoat_dong", "nam_hoc", "hoc_ky");

                    b.ToTable("HoatDongDotXuat", null, t =>
                        {
                            t.HasCheckConstraint("CK_HoatDongDotXuat_HocKy", "[HocKy] >= 1 AND [HocKy] <= 2");
                        });
                });

            modelBuilder.Entity("phucvucongdong.Entities.LichSu", b =>
                {
                    b.Property<int>("lich_su_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lich_su_id"));

                    b.Property<int>("hoat_dong_id")
                        .HasColumnType("int");

                    b.Property<string>("loai_hanh_dong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nguoi_dung_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("thoi_gian_thuc_hien")
                        .HasColumnType("datetime2");

                    b.HasKey("lich_su_id");

                    b.HasIndex("hoat_dong_id");

                    b.HasIndex("nguoi_dung_id");

                    b.ToTable("LichSu", "pvcd");
                });

            modelBuilder.Entity("phucvucongdong.Entities.NguoiDung", b =>
                {
                    b.Property<int>("nguoi_dung_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nguoi_dung_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nguoi_dung_id"));

                    b.Property<string>("ho_ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phong_ban")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("thong_tin_lien_he")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("vai_tro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("nguoi_dung_id");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("phucvucongdong.Entities.SinhVien", b =>
                {
                    b.Property<int>("sinh_vien_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sinh_vien_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sinh_vien_id"));

                    b.Property<string>("lop")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nganh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("nguoi_dung_id")
                        .HasColumnType("int");

                    b.HasKey("sinh_vien_id");

                    b.HasIndex("nguoi_dung_id")
                        .IsUnique()
                        .HasFilter("[nguoi_dung_id] IS NOT NULL");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("phucvucongdong.Entities.TieuChi", b =>
                {
                    b.Property<int>("tieu_chi_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tieu_chi_id"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("danh_muc_id")
                        .HasColumnType("int");

                    b.Property<int?>("diem")
                        .HasColumnType("int");

                    b.Property<string>("mo_ta")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ten_tieu_chi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("tieu_chi_id");

                    b.HasIndex("danh_muc_id");

                    b.ToTable("TieuChi", "pvcd", t =>
                        {
                            t.HasCheckConstraint("CK_TieuChi_Diem", "[Diem] >= 0");
                        });
                });

            modelBuilder.Entity("phucvucongdong.Models.TaiKhoan", b =>
                {
                    b.Property<int>("tai_khoan_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tai_khoan_id"));

                    b.Property<string>("mat_khau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("nguoi_dung_id")
                        .HasColumnType("int");

                    b.Property<string>("phan_quyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ten_dang_nhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("tai_khoan_id");

                    b.HasIndex("nguoi_dung_id")
                        .IsUnique();

                    b.ToTable("TaiKhoan", "pvcd");
                });

            modelBuilder.Entity("ThamGiaSinhVien", b =>
                {
                    b.HasOne("phucvucongdong.Entities.HoatDong", "HoatDong")
                        .WithMany("ThamGiaSinhViens")
                        .HasForeignKey("hoat_dong_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("phucvucongdong.Entities.SinhVien", "SinhVien")
                        .WithMany("ThamGiaSinhViens")
                        .HasForeignKey("sinh_vien_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoatDong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("phucvucongdong.Entities.DangKyGiaoVien", b =>
                {
                    b.HasOne("phucvucongdong.Entities.GiaoVien", "GiaoVien")
                        .WithMany("DangKyGiaoViens")
                        .HasForeignKey("giao_vien_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("phucvucongdong.Entities.HoatDong", "HoatDong")
                        .WithMany()
                        .HasForeignKey("hoat_dong_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("HoatDong");
                });

            modelBuilder.Entity("phucvucongdong.Entities.GiaoVien", b =>
                {
                    b.HasOne("phucvucongdong.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("nguoi_dung_id");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("phucvucongdong.Entities.HoatDong", b =>
                {
                    b.HasOne("phucvucongdong.Entities.TieuChi", "TieuChi")
                        .WithMany("HoatDongs")
                        .HasForeignKey("tieu_chi_id");

                    b.Navigation("TieuChi");
                });

            modelBuilder.Entity("phucvucongdong.Entities.HoatDongDotXuat", b =>
                {
                    b.HasOne("phucvucongdong.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("nguoi_dung_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("phucvucongdong.Entities.LichSu", b =>
                {
                    b.HasOne("phucvucongdong.Entities.HoatDong", "HoatDong")
                        .WithMany()
                        .HasForeignKey("hoat_dong_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("phucvucongdong.Entities.NguoiDung", "NguoiDungs")
                        .WithMany()
                        .HasForeignKey("nguoi_dung_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoatDong");

                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("phucvucongdong.Entities.SinhVien", b =>
                {
                    b.HasOne("phucvucongdong.Entities.NguoiDung", "NguoiDung")
                        .WithOne("SinhVien")
                        .HasForeignKey("phucvucongdong.Entities.SinhVien", "nguoi_dung_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("phucvucongdong.Entities.TieuChi", b =>
                {
                    b.HasOne("phucvucongdong.Entities.DanhMucPVCongDong", "DanhMucPVCongDong")
                        .WithMany("TieuChis")
                        .HasForeignKey("danh_muc_id");

                    b.Navigation("DanhMucPVCongDong");
                });

            modelBuilder.Entity("phucvucongdong.Models.TaiKhoan", b =>
                {
                    b.HasOne("phucvucongdong.Entities.NguoiDung", "NguoiDung")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("phucvucongdong.Models.TaiKhoan", "nguoi_dung_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("phucvucongdong.Entities.DanhMucPVCongDong", b =>
                {
                    b.Navigation("TieuChis");
                });

            modelBuilder.Entity("phucvucongdong.Entities.GiaoVien", b =>
                {
                    b.Navigation("DangKyGiaoViens");
                });

            modelBuilder.Entity("phucvucongdong.Entities.HoatDong", b =>
                {
                    b.Navigation("ThamGiaSinhViens");
                });

            modelBuilder.Entity("phucvucongdong.Entities.NguoiDung", b =>
                {
                    b.Navigation("SinhVien");

                    b.Navigation("TaiKhoan")
                        .IsRequired();
                });

            modelBuilder.Entity("phucvucongdong.Entities.SinhVien", b =>
                {
                    b.Navigation("ThamGiaSinhViens");
                });

            modelBuilder.Entity("phucvucongdong.Entities.TieuChi", b =>
                {
                    b.Navigation("HoatDongs");
                });
#pragma warning restore 612, 618
        }
    }
}
